dist: trusty

language: ruby
rvm:
  - 2.5
  - 2.6
  - jruby
  - truffleruby

services:
  - docker

before_install:
  - export CI_COMMIT=$(echo ${TRAVIS_COMMIT:0:8})
  - echo $CI_COMMIT
  - docker build -t $DOCKER_HUB_USERNAME/mini-go-resto:$CI_COMMIT .
  - docker images
  - 'which ssh-agent || (sudo apt-get update -y && sudo apt-get install -y openssh-client)'
  - eval $(ssh-agent -s)
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

install:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push $DOCKER_HUB_USERNAME/mini-go-resto:$CI_COMMIT
  - ssh $DEPLOYMENT_HOST "docker pull $DOCKER_HUB_USERNAME/mini-go-resto:$CI_COMMIT"

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres